### ISSUE TITLE
74680419-svelte-docker-HMR: error when running

### ISSUE THREAD

**Issue by Jacob-Lasky** [rabelais88/stackoverflow-answers#1]
Hi, thanks for putting up these answers and examples. When I try to run your example [here](https://github.com/rabelais88/stackoverflow-answers/tree/main/74680419-svelte-docker-HMR), I get the following error message:
`Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.`

That error never goes away and `localhost:8080` is always unavailable

Do you have any idea what this is referring to or why it could be happening?

![image](https://user-images.githubusercontent.com/6790237/217382273-31aab2b4-3100-47d6-a3e3-c3cd5516fcd5.png)

**Comment by rabelais88** [comment]
I've just checked it and it runs OK. It has something to do with your revision on configuration. Please post a new question on Stackoverflow if that's the case.
